baseURL = "https://saukratesk.github.io/sturdy-succotash/"
languageCode = "fr"
defaultContentLanguage = "fr"
title = "Mon Site Web"

[params]
  description = "Mon site web personnel avec Hugo"
  theme = "my-theme"

[languages]
  [languages.fr]
    languageName = "Français"
    weight = 1
  [languages.en]
    languageName = "English"
    weight = 2